spring.application.name=Inventario

# DataSource SQLite
spring.datasource.url=jdbc:sqlite:inventario.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=com.marcofidel_dev.inventario.infrastructure.config.SQLiteDialectCustom
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQLite specific
spring.jpa.properties.hibernate.dialect=com.marcofidel_dev.inventario.infrastructure.config.SQLiteDialectCustom
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# Logging
logging.level.com.marcofidel_dev.inventario=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# POS configuration
pos.descuento.max.colaborador=10
pos.comprobante.empresa.nombre=Alejandria Make-Up
pos.comprobante.empresa.direccion=Puerto Gaitan, Meta
pos.comprobante.empresa.telefono=323 650 3252
pos.comprobante.formato=TERMICO_80MM
pos.caja.requerir-apertura=true

